name: Dependabot Critical Alerts to Slack

on:
  workflow_dispatch: # allows manual run (for backfill)
  dependabot_alert:
    types: [created, reopened] # real-time alerts

jobs:
  send-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Backfill or handle new alert
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          send_to_slack() {
            package="$1"
            summary="$2"
            url="$3"
            payload=$(jq -n \
              --arg package "$package" \
              --arg summary "$summary" \
              --arg url "$url" \
              '{text: "🚨 *Critical Dependabot Alert*\n*Package:* \($package)\n*Issue:* \($summary)\n<\($url)|View Alert>"}')
            curl -s -X POST -H 'Content-type: application/json' \
                 --data "$payload" "$WEBHOOK_URL"
          }

          if [ "$EVENT_NAME" = "dependabot_alert" ]; then
            # Real-time mode
            severity="${{ github.event.alert.severity }}"
            if [ "$severity" = "critical" ]; then
              send_to_slack \
                "${{ github.event.alert.dependency.package.name }}" \
                "${{ github.event.alert.security_advisory.summary }}" \
                "${{ github.event.alert.html_url }}"
            else
              echo "Alert severity is not critical — skipping."
            fi
          else
            # Backfill mode (manual run)
            echo "Fetching all historical critical alerts..."
            curl -s -H "Authorization: Bearer $GH_TOKEN" \
                 -H "Accept: application/vnd.github+json" \
                 "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts" \
            | jq -c '.[] | select(.severity=="critical")' \
            | while read -r alert; do
                package=$(echo "$alert" | jq -r '.dependency.package.name')
                summary=$(echo "$alert" | jq -r '.security_advisory.summary')
                url=$(echo "$alert" | jq -r '.html_url')
                send_to_slack "$package" "$summary" "$url"
              done
          fi
